### ISSUE TITLE
api.get: no way to pass method_version

### ISSUE THREAD

**Issue by melkor217** [vinnicc/dota#20]
https://github.com/vinnicc/dota/blob/55c003300e00cfeac0b04f2ad423024b9b24828c/lib/dota/api/client.rb#L103

**Comment by bodrovis** [comment]
@vinnicc Thoughts?

**Comment by vinnicc** [comment]
Will add another method in the config block to set a default, and for single requests allow a `api_version` key to be merged in the params hash. In the meantime you can to do:

```ruby
api.get("IDOTA2Match_570", "GetMatchDetails", { match_id: 789645621 }, "V002")
```

**Comment by vinnicc** [comment]
Should we change the default current "V001" to "v1"? Steam seems to strip off leading "0"s and "V" can be lowercase too so even "v000000000000001" works.
