### ISSUE TITLE
Mapping errors

### ISSUE THREAD

**Issue by MichaelSnowden** [vinnicc/dota#22]
>> p.hero
	NoMethodError: undefined method `[]' for nil:NilClass
		from /Library/Ruby/Gems/2.0.0/gems/dota-0.0.18/lib/dota/api/hero.rb:10:in `initialize'
		from /Library/Ruby/Gems/2.0.0/gems/dota-0.0.18/lib/dota/api/basic_player.rb:28:in `new'
		from /Library/Ruby/Gems/2.0.0/gems/dota-0.0.18/lib/dota/api/basic_player.rb:28:in `hero'
		from /Users/michael.snowden/RoR/dota2/app/views/matches/show.html.haml:8:in `block in _app_views_matches_show_html_haml__790562918000300060_70277494873540'

Also, I can't access the mapping:

    >>  Dota::API::Hero::MAPPING
	NoMethodError: undefined method `[]' for nil:NilClass
		from /Library/Ruby/Gems/2.0.0/gems/dota-0.0.18/lib/dota/api/hero.rb:10:in `initialize'
		from /Library/Ruby/Gems/2.0.0/gems/dota-0.0.18/lib/dota/api/basic_player.rb:28:in `new'
		from /Library/Ruby/Gems/2.0.0/gems/dota-0.0.18/lib/dota/api/basic_player.rb:28:in `hero'
		from /Users/michael.snowden/RoR/dota2/app/views/matches/show.html.haml:8:in `block in _app_views_matches_show_html_haml__790562918000300060_70277494873540'

However, I see the mapping file under `/Library/Ruby/Gems/2.0.0/gems/dota-0.0.18/lib/dota/utils/mapped.rb`. 

This is preventing me from accessing the hero a player uses, such as `player.hero`. However, I can still access heroes without players, such as `Dota.api.heroes(43)`

**Comment by vinnicc** [comment]
Can you provide more context? It would help to know how `p` is assigned, for instance.

For the other one, it's a class method `Dota::API::Hero.mapping`.

**Comment by MichaelSnowden** [comment]
p is just a regular player I get from match details.

**Comment by vinnicc** [comment]
What's the Match ID?

**Comment by MichaelSnowden** [comment]
1532971161

**Comment by MichaelSnowden** [comment]
It seems to work for other matches: I tried the next one up.

**Comment by bodrovis** [comment]
@vinnicc Here it is http://www.dotabuff.com/matches/1532971161 This is a match that haven't even started and one of the players haven't choose a hero. Therefore an error is returned when trying to fetch it.

**Comment by bodrovis** [comment]
https://github.com/vinnicc/dota/blob/master/lib/dota/api/basic_player.rb#L27 we can just check if `raw["hero_id"]` is set and return `nil` if it is not there.

**Comment by vinnicc** [comment]
@MichaelSnowden Got it.

@bodrovis Thanks. I wish we can avoid `nil` here. Does this happen only in that case? If so, I'm thinking of returning a `PendingHero` instead so nothing breaks.

**Comment by bodrovis** [comment]
Well, unfortunately I can't be sure :) Probably if a new hero is released that the gem has no idea of this error will happen too. Yeah, null object pattern might be nice here.

**Comment by vinnicc** [comment]
Okay, fixed!
