### ISSUE TITLE
undefined method `merge'

### ISSUE THREAD

**Issue by tugsbayarg** [vinnicc/dota#24]
Hello,

First thanks for gem.

I've error in 
/home/tugsbayar/.rvm/gems/ruby-2.2.2/gems/dota-0.0.19/lib/dota/api/live_match.rb:48:in `raw_side'
when I tried to get dire from live_match.

There's dire and radiant in raw view...

How can I fix it ?

**Comment by vinnicc** [comment]
@tugsbayarg thanks, what's the match ID?

**Comment by bodrovis** [comment]
I believe that's too late as live match is over atm. Some raw data would be helpful if any available.

**Comment by tugsbayarg** [comment]
unfortunately I can't reproduce error again. 
it's working without error now.
We can close this issue currently. I'll post raw data next time if it occur again.
