### ISSUE TITLE
League item_def

### ISSUE THREAD

**Issue by tugsbayarg** [vinnicc/dota#28]
Hello.

I want to get item_def field value from league. But there's no field available in League object.

How can I access to the field?

Thanks for help.

**Comment by tugsbayarg** [comment]
I got value from object.raw["itemdef"]

Wondering if there's better way ...

**Comment by vinnicc** [comment]
`raw` works as a fallback, but we can add a method for this one. Any name suggestions? I honestly don't know what it's used for.

**Comment by tugsbayarg** [comment]
It could be used to get additional information about tournament (Currently I'm using it to get league logo.). To be honest in league listing service there's not much info there.

I guess itemdef should be ok for name :D

**Comment by vinnicc** [comment]
Added `#itemdef` as of https://github.com/vinnicc/dota/commit/4cd71122911f4cfbbcfadd75ca8070de32ee1a76.
