### ISSUE TITLE
How to filter League Tournament Level ?

### ISSUE THREAD

**Issue by 7urkm3n** [vinnicc/dota#34]
I found this in api/leagues. Is there way to filter level of league ? I couldn't figure it out somehow.  

```
      TIERS = {
        1 => "Amateur",
        2 => "Professional",
        3 => "Premier"
      }
```

Thank You!

**Comment by vinnicc** [comment]
I'm not aware if Valve's API did happen to support this after all this time. In any case, there's no built-in support in the gem yet. However, you can pass [arbitrary parameters](https://github.com/vinnicc/dota#custom-requests) as needed.
