### ISSUE TITLE
Update abilities.yml to 7.00

### ISSUE THREAD

**Issue by Gremglee** [vinnicc/dota#35]
Hi!

Retrieving history of leveled abilities fails now cause of missing ability ids from new talent system added in patch 7.00. I want to update /data/ability.yml according to patch 7.00. But I stuck on finding a simple way to do it. How did you create this file initially?

**Comment by vinnicc** [comment]
Hi, I just copied from one of the dumps around here which seemed to have good community support that time. If you search for [5043 lina_laguna_blade](https://github.com/search?utf8=%E2%9C%93&q=5043+lina_laguna_blade&type=Code&ref=searchresults) you'll get similar content but I'm not sure which ones have been updated to reflect 7.00 yet.

**Comment by vinnicc** [comment]
@Gremglee Check out https://github.com/ya-kmet/dota2-static/blob/master/data/abilities.yml :)

**Comment by Gremglee** [comment]
Thank you a lot! It is a really helpful and fast update!
