### ISSUE TITLE
How to get abilities for particular Hero ?

### ISSUE THREAD

**Issue by s8sachin** [vinnicc/dota#36]
Firstly, Huge thanks for this gem. 
I just wanted to know how to get abilities for particular hero ? 
is there an end point for that?
I don't see hero_id in abilities.
please help me with this :)

**Comment by bodrovis** [comment]
I do not think there is a way to do it atm, as abilities have only internal ids https://github.com/vinnicc/dota/blob/master/data/ability.yml and are not related to heroes

**Comment by vinnicc** [comment]
Considering this issue resolved. Thanks @bodrovis for filling in :-)
