### ISSUE TITLE
Option "after" in Dota.api.matches()

### ISSUE THREAD

**Issue by Gremglee** [vinnicc/dota#37]
This option has a confusing description - it does not return match IDs equal or greater than this. On the contrary, it returns match IDs equal or smaller than this.

https://wiki.teamfortress.com/wiki/WebAPI/GetMatchHistory - this wiki explains it right: "Start searching for matches equal to or older than this match ID."

Or you can try it with my example:
```
Dota.api.matches(player_id: 454215083, after: 3397884924).map(&:id)
=> [3397906921, 3397884924, 3397325005, 3397310018, 3397249302, 3395653392, 3395006949, 3394906999, 3394782080, 3394657020, 3394585777, 3394520695]
Dota.api.matches(player_id: 454215083, after: 3397884924).count
=> 11
Dota.api.matches(player_id: 454215083, after: 3394585777).count
=> 2
```

**Comment by vinnicc** [comment]
Fixed as of #38.
