### ISSUE TITLE
Non-existent match mode id

### ISSUE THREAD

**Issue by bodrovis** [vinnicc/dota#6]
Hello once again.

I am fetching info about a basic All Pick match like this:

```
match = Dota.api.matches(1325446180)
```

and then try to get mode id:

```
match.mode # => nil
match.mode_id # => 22
```

However there is no such key here: https://github.com/vinnicc/dota/blob/b04125627970f7e164cd5af513c061c5009eb249/lib/dota/api/basic_match.rb#L18

Here is this match on DotaBuff: http://www.dotabuff.com/matches/1325446180

I am doing something wrong or has those ids changed?

**Comment by vinnicc** [comment]
I haven't been up-to-date with the latest patches. Would it make sense to add `22 => "All Pick"` here?

**Comment by bodrovis** [comment]
Well, seems so but I don't know what else has changed :( Where did you get this data from? TeamFortress wiki was not updated for some time.

**Comment by vinnicc** [comment]
From other libraries, for instance: https://github.com/kronusme/dota2-api/blob/master/data/mods.json

Yeah I find that wiki to be unreliable now. I tried searching https://github.com/dotabuff/d2vpk for a list, but I have no idea what to look for exactly.

**Comment by bodrovis** [comment]
Okay, this appeared to be Ranked All Pick. Here https://github.com/yasp-dota/yasp/blob/fdc614688116ddc860a0cf73249a9e6eb5ec77f2/sources.json is the great source of various up-to-date info. PR is sent.
